config/routes.rb
VirtualPhone::Application.routes.draw do

  resources :numbers
  resources :phones do
    collection do
      post 'incoming_call'
      post 'incoming_sms'
    end
  end

  root :to => "numbers#index"

end

app/models/mock_number.rb
class MockNumber < Number

  def adapter_class
    MockAdapter
  end
end

app/models/number.rb
class Number < ActiveRecord::Base
  validates :number, :presence => true, :uniqueness => true, :phony_plausible => true
  validates :prefix, :presence => true, :format => { :with => /\A\d{3}\z/ }
  validates :phone, :presence => true
  belongs_to :phone

  before_validation :provision_number, :on => :create, :unless => :number?

  after_destroy :release_number

  phony_normalize :number, :default_country_code => "CA"

  accepts_nested_attributes_for :phone

  attr_accessor :adapter

  def self.find_by_number(number)
    super(number) || super("1#{number}")
  end

  def provision_number
    return unless prefix
    provisioning_response = adapter.provision_number(prefix)
    self.number = provisioning_response.number
    self.adapter_identifier = provisioning_response.adapter_identifier
  end

  def release_number
    adapter.release_number(self)
  end

  def forward_to
    Phony.formatted(phone.number, :format => :international, :spaces => "") if phone
  end

  def incoming_call(from)
    adapter.forward_call(self, from)
  end

  def incoming_sms(from, text)
    adapter.forward_sms(self, from, text)
  end

  def adapter_class
    raise NotImplementedError, "adapter_class is not implemented for #{self.inspect}"
  end

  def adapter
    @adapter ||= adapter_class.send(:new)
  end

  def phone_attributes=(phone_attributes)
    normalized_number = PhonyRails.normalize_number(phone_attributes[:number], :country_code => phone_attributes[:country_code])
    self.phone = Phone.find_or_initialize_by_number(normalized_number)
    self.phone.country_code ||= phone_attributes[:country_code]
  end
end

app/models/number_factory.rb
class NumberFactory
  def self.build_number(params)
    adapter_class.new(params)
  end

  def self.adapter_class
    case ENV['ADAPTER']
    when 'tropo'
      TropoNumber
    when 'twilio'
      TwilioNumber
    else
      MockNumber
    end
  end
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  validates :number, :uniqueness => true, :presence => true, :phony_plausible => true
  has_many :numbers
  phony_normalize :number
end

app/models/tropo_number.rb
class TropoNumber < Number

  def adapter_class
    TropoAdapter
  end
end

app/models/twilio_number.rb
class TwilioNumber < Number

  def adapter_class
    TwilioAdapter
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/numbers_controller.rb
class NumbersController < ApplicationController
  before_filter :build_number, :only => [:new, :create]

  def index
    @numbers = Number.all
  end

  def new
    @number.phone = Phone.new
  end
  
  def show
    @number = Number.find(params[:id])
  end

  def create
    if @number.save
      flash[:notice] = "Number Successfully Created, Please Allow up to 10 minutes for number to provision"
      redirect_to number_path(@number)
    else
      render :new
    end
  end

  def edit
    @number = Number.find(params[:id])
  end

  def update
    @number = Number.find(params[:id])
    if @number.update_attributes(params[:number])
      flash[:notice] = "Number Successfully Updated"
      redirect_to numbers_path
    else
      render :edit
    end
  end

  def destroy
    @number = Number.find(params[:id])
    if @number.destroy
      flash[:notice] = "Number Successfully Deleted"
      redirect_to numbers_path
    else
      raise "Number not destroyed #{@number.inspect}"
    end
  end

  protected
  def build_number
    @number = NumberFactory.build_number(params[:number])
  end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  def incoming_call
    adapter = AdapterFactory.create(params)
    number = Number.find_by_number adapter.to
    render adapter.response_type => number.incoming_call(adapter.from)
  end

  def incoming_sms
    adapter = AdapterFactory.create(params)
    number = Number.find_by_number adapter.to
    render adapter.response_type => number.incoming_sms(adapter.from, adapter.message_content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    #when :notice then "alert-info"
    when :notice then "alert-success"
    when :error then "alert-error"
    when :alert then nil
    when :success then "alert-success"
    end
  end
end

app/helpers/numbers_helper.rb
module NumbersHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert <%= flash_class(name) %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-inverse navbar-static-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Virtual Phone", root_path, :class => 'brand' %>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li>
          <%= link_to('Numbers', numbers_path)  %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Phones" %></title>
    <meta name="description" content="">
    <meta name="author" content="Andrew Narkewicz">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <%= render 'layouts/messages' %>
    <%= render 'layouts/navigation' %>
    <div class="container-fluid">
      <%= yield %>
      <footer>
      </footer>
    </div>
  </body>
<html>

app/views/numbers/_phone_fields.html.erb
<%= form.semantic_fields_for :phone do |phone| %>
  <%= phone.input :country_code, :label => "Country", :as => :country %>
  <%= phone.input :number %>
<% end %>

app/views/numbers/edit.html.erb
<%= semantic_form_for @number, :url => number_path, :as => :number do |form| %>
  <div class="number_info">
    <%= @number.number.phony_formatted %>
  </div>
  <%= form.inputs "Is Forwarded To" do%>
    <%= render :partial => "phone_fields", :locals => {:form => form} %>
  <%end%>
  <%= form.actions do %>
    <%= form.action :submit, :label => "Update Number" %>
    <%= form.action :cancel, :label => "Cancel", :as => :link %>
  <%end%>
<% end %>

app/views/numbers/index.html.erb
<div class="action_items visible-desktop">
  <%= link_to 'Add New Number', new_number_path, :class => "btn"%>
</div>
<div class="hidden-desktop">
  <%= link_to 'Add New Number', new_number_path, :class => "btn btn-block"%>
</div>
<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Number</th>
      <th>To</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @numbers.each do |number| %>
      <tr>
        <td><%= number.number.phony_formatted %></td>
        <td><%= number.phone.number.phony_formatted %></td>
        <td><%= link_to 'view', number_path(number) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/numbers/new.html.erb
<%= semantic_form_for @number, :url => numbers_path, :as => :number do |form| %>
  <%= form.inputs "Setup a Phone Number with" do %>
    <%= form.input :prefix, :label => "Area Code", :input_html => { :class => "input-mini" } %>
  <%end%>
  <%= form.inputs "That Forwards To" do%>
    <%= render :partial => "phone_fields", :locals => {:form => form} %>
  <%end%>
  <%= form.actions do %>
    <%= form.action :submit, :label => "Create Number" %>
    <%= form.action :cancel, :label => "Cancel", :as => :link %>
  <%end%>
<% end %>

app/views/numbers/show.html.erb
<div class="action_items visible-desktop">
  <%= link_to 'Edit Number', edit_number_path(@number), :class => "btn" %>
  <%= link_to 'Delete Number', number_path(@number), :confirm => "Are you sure you want to delete #{@number.number}", :method => :delete, :class => "btn btn-danger" %>
</div>
<div class="clearfix"></div>
<div class="number_info">
  <%= @number.number.phony_formatted %>
</div>
<div class="phone_info">
  <legend>Is Forwarded To</legend>
  <%= @number.phone.number.phony_formatted %>
</div>
<div class="hidden-desktop">
  <%= link_to 'Edit Number', edit_number_path(@number), :class => "btn btn-block" %>
  <%= link_to 'Delete Number', number_path(@number), :confirm => "Are you sure you want to delete #{@number.number}", :method => :delete, :class => "btn btn-danger btn-block" %>
</div>